name: ci.yml
on:
  workflow_dispatch:

#  pull_request:
#    branches:
#      - main

# sets working directory for all the jobs
defaults:
  run:
    working-directory: uksford-api

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew itTest
          

    
    
