name: ci.yml
on:
  pull_request:
    branches:
      - main

# sets working directory for all the jobs
defaults:
  run:
    working-directory: uksford-api

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew test

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: run-unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Start uksford_db container service
        run: |
          cd docker
          docker compose up -d uksford_db

      - name: Check uksford_db health
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
          max-retries: 30
          retry-interval: 10
          compose-file: "uksford-api/docker/compose.yml"

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew itTest
          

    
    
